### ISSUE TITLE
(ice-9 match) warnings

### ISSUE THREAD

**Issue by a-sassmannshausen** [flatwhatson/flycheck-guile#1]
Hello,

This is an excellent checker, thank you for providing it!

I've noticed that the match macro from (ice-9 match) triggers warnings for the "unused variable `failure'". Is this a user error on my part? I'm not defining failure anywhere so I'm not sure where the checker is getting it from… the macro itself perhaps?

Alex

**Comment by flatwhatson** [comment]
It's not user error, the warning is for a variable internal to the macro.  I've seen similar false-positive "unused variable" warnings from other macros too (eg. (ice-9 peg) produces lots of these).  This needs to be fixed upstream, probably the compiler needs to either suppress them, or report the macro *definition* as the location of the error instead of the macro expansion.

Unfortunately there's no way that I can detect and suppress these from the checker.  Until the compiler is improved, we need to either accept/ignore the false positives or disable the "unused-variable" warning in the flycheck-guile configuration.

**Comment by a-sassmannshausen** [comment]
Ah, that's a shame: neither solution easily within our reach seems a particularly desirable outcome. In any case, thanks for confirming what I saw — knowing the cause is very useful to me already!

Alex

**Comment by flatwhatson** [comment]
I've added a section to the README describing how to configure which warnings are reported.  Thanks for your report!
